const supabase = require('../config/supabaseClient');
const { prisma } = require('../config/db');

/**
 * @desc    Register a new user
 * @route   POST /api/v1/auth/register
 * @access  Public
 */
const register = async (req, res) => {
  const {
    name,
    email,
    password,
    whatsappNumber,
    nic,
    guardianName,
    guardianNumber,
    address
  } = req.body;

  // 1. Sign up user via Supabase Auth
  const { data: authData, error: authError } = await supabase.auth.signUp({
    email,
    password,
    options: {
      data: {
        name,
      }
    }
  });

  if (authError) {
    const error = new Error(authError.message);
    error.statusCode = 400;
    throw error;
  }

  // Ensure the user doesn't already exist in Prisma Studnets table
  const existingStudent = await prisma.student.findFirst({
    where: { Email: email }
  });

  if (existingStudent) {
    const error = new Error('Student already exists with that email');
    error.statusCode = 400;
    throw error;
  }

  // 2. Create Student in database (id must match auth.users id)
  const student = await prisma.student.create({
    data: {
      id: authData.user.id, // Maps to the UUID generated by Supabase
      Name: name,
      Email: email,
      Watsapp_Number: whatsappNumber,
      NIC: nic ? parseFloat(nic) : null,
      Gurdian_s_Name: guardianName,
      Gurdians_Number: guardianNumber,
      Address: address,
      // Student_ID is auto-incremented by Prisma's @default(autoincrement())
    },
  });

  // Convert BigInt to string for JSON serialization
  const serializedStudent = {
    ...student,
    Student_ID: student.Student_ID.toString(),
    NIC: student.NIC ? student.NIC.toString() : null,
  };

  res.status(201).json({
    success: true,
    token: authData.session?.access_token || null,
    user: serializedStudent,
    message: authData.session ? 'Registration successful' : 'Registration successful! Please verify your email.',
  });
};

/**
 * @desc    Login user
 * @route   POST /api/v1/auth/login
 * @access  Public
 */
const login = async (req, res) => {
  const { email, password } = req.body;

  if (!email || !password) {
    const error = new Error('Please provide email and password');
    error.statusCode = 400;
    throw error;
  }

  // 1. Sign in via Supabase Auth
  const { data: authData, error: authError } = await supabase.auth.signInWithPassword({
    email,
    password,
  });

  if (authError || !authData.user) {
    const error = new Error(authError?.message || 'Invalid credentials');
    error.statusCode = 401;
    throw error;
  }

  // 2. Fetch extended profile from Student table
  const student = await prisma.student.findUnique({
    where: { id: authData.user.id },
  });

  if (!student) {
    const error = new Error('User profile not found');
    error.statusCode = 404;
    throw error;
  }

  // Convert BigInts for JSON serialization
  const serializedStudent = {
    ...student,
    Student_ID: student.Student_ID.toString(),
    NIC: student.NIC ? student.NIC.toString() : null,
  };

  res.status(200).json({
    success: true,
    token: authData.session.access_token,
    user: serializedStudent,
  });
};

/**
 * @desc    Get current logged-in user
 * @route   GET /api/v1/auth/me
 * @access  Private
 */
const getMe = async (req, res) => {
  // Convert BigInts for JSON serialization
  const serializedStudent = {
    ...req.user,
    Student_ID: req.user.Student_ID.toString(),
    NIC: req.user.NIC ? req.user.NIC.toString() : null,
  };

  res.status(200).json({ success: true, user: serializedStudent });
};

module.exports = { register, login, getMe };
